[build]
  base = "ai-banking"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://unipay-production-api.loca.lt"

[[plugins]]
  package = "@netlify/plugin-nextjs"
