[build]
  base = "ai-banking"
  command = "npm run build"
  publish = ".next"

[build.environment]
  NEXT_PUBLIC_API_URL = "https://9c92a173e4bb0f.lhr.life"



[[plugins]]
  package = "@netlify/plugin-nextjs"
