spring:
  application:
    name: globalpay

  data:
    mongodb:
      uri: mongodb+srv://suriya:Suriya%401486@suriya.vhhmcht.mongodb.net/globalpay?retryWrites=true&w=majority&tls=true&appName=suriya

server:
  port: 8080

app:
  jwt:
    secret: aVeryLongAndSecureSecretKeyThatNeedsToBeAtLeast32BytesLongForHS256AlgorithmGlobalPaySystem2026
    expiration: 86400000 # 24 hours in ms
  groq:
    api-key: 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
    url: https://api.groq.com/openai/v1/chat/completions
